"""empty message

Revision ID: 15bcd8049d3a
Revises: 
Create Date: 2023-09-26 12:51:04.678710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bcd8049d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_subjs', sa.String(length=225), nullable=False))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    with op.batch_alter_table('examina', schema=None) as batch_op:
        batch_op.drop_column('exclude_subjs')

    # ### end Alembic commands ###
