"""empty message

Revision ID: 66f13bddba09
Revises: 8745f432acdf
Create Date: 2023-10-26 12:38:26.485375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f13bddba09'
down_revision = '8745f432acdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_result', schema=None) as batch_op:
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
