"""empty message

Revision ID: 8745f432acdf
Revises: db7641424559
Create Date: 2023-10-25 23:39:58.746931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8745f432acdf'
down_revision = 'db7641424559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_result_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('publish_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examina', schema=None) as batch_op:
        batch_op.drop_column('publish_date')
        batch_op.drop_column('publish_result_status')

    # ### end Alembic commands ###
